_format_version: "3.0"
services:
  - connect_timeout: 60000
    host: example.com
    name: example2
    port: 444
    protocol: https
    read_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        name: example-route2
        paths:
          - /example
          - /example-route
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        strip_path: true
    write_timeout: 60000
